#ifndef PERIPH_INC_CUSTOM_PERIPH_H_
#define PERIPH_INC_CUSTOM_PERIPH_H_

#include <io.h>
/* MIPI DSI TX controller regs */

#define MIPI_DSI_TX_CTRL_BASE                       0
#define MIPI_DSI_TX_CTRL_ASSEMBLER_ENABLE_OFST      (0)
#define MIPI_DSI_TX_CTRL_ASSEMBLER_ENABLE_MASK      ((1) << MIPI_DSI_TX_CTRL_ASSEMBLER_ENABLE_OFST)
#define MIPI_DSI_TX_CTRL_LANES_ENABLE_OFST          (1)
#define MIPI_DSI_TX_CTRL_LANES_ENABLE_MASK          ((1) << MIPI_DSI_TX_CTRL_LANES_ENABLE_OFST)
#define MIPI_DSI_TX_CTRL_CLK_ENABLE_OFST            (2)
#define MIPI_DSI_TX_CTRL_CLK_ENABLE_MASK            ((1) << MIPI_DSI_TX_CTRL_CLK_ENABLE_OFST)
#define MIPI_DSI_TX_CTRL_SEND_CMD_OFST            	(3)
#define MIPI_DSI_TX_CTRL_SEND_CMD_MASK              ((1) << MIPI_DSI_TX_CTRL_SEND_CMD_OFST)
#define MIPI_DSI_TX_CTRL_LANES_NUMBER_OFST          (8)
#define MIPI_DSI_TX_CTRL_LANES_NUMBER_MASK          ((3) << MIPI_DSI_TX_CTRL_LANES_NUMBER_OFST)
#define MIPI_DSI_TX_CTRL_LANES_NUMBER_MASK_0        ((0) << MIPI_DSI_TX_CTRL_LANES_NUMBER_OFST)
#define MIPI_DSI_TX_CTRL_LANES_NUMBER_MASK_1        ((1) << MIPI_DSI_TX_CTRL_LANES_NUMBER_OFST)
#define MIPI_DSI_TX_CTRL_LANES_NUMBER_MASK_2        ((2) << MIPI_DSI_TX_CTRL_LANES_NUMBER_OFST)
#define MIPI_DSI_TX_CTRL_LANES_NUMBER_MASK_3        ((3) << MIPI_DSI_TX_CTRL_LANES_NUMBER_OFST)

#define MIPI_DSI_TX_ISR_BASE                        4
#define MIPI_DSI_TX_ISR_PIX_BUFF_UNDERFLOW_OFST     (0)
#define MIPI_DSI_TX_ISR_PIX_BUFF_UNDERFLOW_MASK     ((1) << MIPI_DSI_TX_ISR_PIX_BUFF_UNDERFLOW_OFST)
#define MIPI_DSI_TX_ISR_LANES_READY_OFST            (1)
#define MIPI_DSI_TX_ISR_LANES_READY_MASK            ((1) << MIPI_DSI_TX_ISR_LANES_READY_OFST)
#define MIPI_DSI_TX_ISR_CLK_READY_OFST              (2)
#define MIPI_DSI_TX_ISR_CLK_READY_MASK              ((1) << MIPI_DSI_TX_ISR_CLK_READY_OFST)
#define MIPI_DSI_TX_ISR_LANES_ACTINE_OFST           (3)
#define MIPI_DSI_TX_ISR_LANES_ACTINE_MASK           ((1) << MIPI_DSI_TX_ISR_LANES_ACTINE_OFST)
#define MIPI_DSI_TX_ISR_LANES_UNACTINE_OFST         (4)
#define MIPI_DSI_TX_ISR_LANES_UNACTINE_MASK         ((1) << MIPI_DSI_TX_ISR_LANES_UNACTINE_OFST)

#define MIPI_DSI_TX_IER_BASE                        8
#define MIPI_DSI_TX_IER_PIX_BUFF_UNDERFLOW_OFST     (0)
#define MIPI_DSI_TX_IER_PIX_BUFF_UNDERFLOW_MASK     ((1) << MIPI_DSI_TX_IER_PIX_BUFF_UNDERFLOW_OFST)
#define MIPI_DSI_TX_IER_LANES_READY_OFST            (1)
#define MIPI_DSI_TX_IER_LANES_READY_MASK            ((1) << MIPI_DSI_TX_IER_LANES_READY_OFST)
#define MIPI_DSI_TX_IER_CLK_READY_OFST              (2)
#define MIPI_DSI_TX_IER_CLK_READY_MASK              ((1) << MIPI_DSI_TX_IER_CLK_READY_OFST)

#define MIPI_DSI_TX_TR1_BASE                        12
#define MIPI_DSI_TX_TR1_TLPX_TIMEOUT_OFST           (16)
#define MIPI_DSI_TX_TR1_TLPX_TIMEOUT_MASK           ((0xff) << MIPI_DSI_TX_TR1_TLPX_TIMEOUT_OFST)
#define MIPI_DSI_TX_TR1_HS_PREPARE_TIMEOUT_OFST     (8)
#define MIPI_DSI_TX_TR1_HS_PREPARE_TIMEOUT_MASK     ((0xff) << MIPI_DSI_TX_TR1_HS_PREPARE_TIMEOUT_OFST)
#define MIPI_DSI_TX_TR1_HS_EXIT_TIMEOUT_OFST        (0)
#define MIPI_DSI_TX_TR1_HS_EXIT_TIMEOUT_MASK        ((0xff) << MIPI_DSI_TX_TR1_HS_EXIT_TIMEOUT_OFST)

#define MIPI_DSI_TX_TR2_BASE                        16
#define MIPI_DSI_TX_TR2_HS_GO_TIMEOUT_OFST          (8)
#define MIPI_DSI_TX_TR2_HS_GO_TIMEOUT_MASK          ((0xff) << MIPI_DSI_TX_TR2_HS_GO_TIMEOUT_OFST)
#define MIPI_DSI_TX_TR2_HS_TRAIL_TIMEOUT_OFST       (0)
#define MIPI_DSI_TX_TR2_HS_TRAIL_TIMEOUT_MASK       ((0xff) << MIPI_DSI_TX_TR2_HS_TRAIL_TIMEOUT_OFST)

#define MIPI_DSI_TX_CMD_BASE                        20
#define MIPI_DSI_TX_CMD_REG_OFST          			(0)
#define MIPI_DSI_TX_CMD_REG_MASK          			((0xff) << MIPI_DSI_TX_CMD_REG_OFST)

#endif
