# TCL File Generated by Component Editor 18.0
# Sun Mar 24 21:16:52 MSK 2019
# DO NOT MODIFY


# 
# avl_st_vid_2_st "Avalon ST Video To Avalon ST" v1.0
#  2019.03.24.21:16:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avl_st_vid_2_st
# 
set_module_property DESCRIPTION ""
set_module_property NAME avl_st_vid_2_st
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon ST Video To Avalon ST"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avl_st_video_2_avl_st_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_st_video_2_avalon_st.v VERILOG PATH ../../rtl/avalon_st_video_2_avalon_st.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avl_st_video_2_avl_st_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_st_video_2_avalon_st.v VERILOG PATH ../../rtl/avalon_st_video_2_avalon_st.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point out_avl_st
# 
add_interface out_avl_st avalon_streaming start
set_interface_property out_avl_st associatedClock clock
set_interface_property out_avl_st associatedReset reset_n
set_interface_property out_avl_st dataBitsPerSymbol 8
set_interface_property out_avl_st errorDescriptor ""
set_interface_property out_avl_st firstSymbolInHighOrderBits true
set_interface_property out_avl_st maxChannel 0
set_interface_property out_avl_st readyLatency 0
set_interface_property out_avl_st ENABLED true
set_interface_property out_avl_st EXPORT_OF ""
set_interface_property out_avl_st PORT_NAME_MAP ""
set_interface_property out_avl_st CMSIS_SVD_VARIABLES ""
set_interface_property out_avl_st SVD_ADDRESS_GROUP ""

add_interface_port out_avl_st out_avl_st_endofpacket endofpacket Output 1
add_interface_port out_avl_st out_avl_st_data data Output 32
add_interface_port out_avl_st out_avl_st_ready ready Input 1
add_interface_port out_avl_st out_avl_st_startofpacket startofpacket Output 1
add_interface_port out_avl_st out_avl_st_valid valid Output 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n rst_n reset_n Input 1


# 
# connection point in_avl_st
# 
add_interface in_avl_st avalon_streaming end
set_interface_property in_avl_st associatedClock clock
set_interface_property in_avl_st associatedReset reset_n
set_interface_property in_avl_st dataBitsPerSymbol 8
set_interface_property in_avl_st errorDescriptor ""
set_interface_property in_avl_st firstSymbolInHighOrderBits true
set_interface_property in_avl_st maxChannel 0
set_interface_property in_avl_st readyLatency 0
set_interface_property in_avl_st ENABLED true
set_interface_property in_avl_st EXPORT_OF ""
set_interface_property in_avl_st PORT_NAME_MAP ""
set_interface_property in_avl_st CMSIS_SVD_VARIABLES ""
set_interface_property in_avl_st SVD_ADDRESS_GROUP ""

add_interface_port in_avl_st in_avl_st_data data Input 24
add_interface_port in_avl_st in_avl_st_valid valid Input 1
add_interface_port in_avl_st in_avl_st_endofpacket endofpacket Input 1
add_interface_port in_avl_st in_avl_st_startofpacket startofpacket Input 1
add_interface_port in_avl_st in_avl_st_ready ready Output 1

