# TCL File Generated by Component Editor 18.0
# Sun Mar 24 20:35:45 MSK 2019
# DO NOT MODIFY


# 
# dsi_tx_controller "MIPI DSI TX  controller" v1.0
#  2019.03.24.20:35:45
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module dsi_tx_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME dsi_tx_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "MIPI DSI TX  controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dsi_tx_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dphy_tx_hs_lane.sv SYSTEM_VERILOG PATH ../../rtl/dphy_tx_hs_lane.sv
add_fileset_file dphy_tx_lane_full.sv SYSTEM_VERILOG PATH ../../rtl/dphy_tx_lane_full.sv
add_fileset_file dphy_tx_lanes_controller.sv SYSTEM_VERILOG PATH ../../rtl/dphy_tx_lanes_controller.sv
add_fileset_file dsi_tx_packets_assembler.v VERILOG PATH ../../rtl/dsi_tx_packets_assembler.v
add_fileset_file dsi_tx_pixel_buffer.v VERILOG PATH ../../rtl/dsi_tx_pixel_buffer.v
add_fileset_file dsi_tx_regs.v VERILOG PATH ../../rtl/dsi_tx_regs.v
add_fileset_file dsi_tx_top.v VERILOG PATH ../../rtl/dsi_tx_top.v TOP_LEVEL_FILE
add_fileset_file fifo_to_lane_bridge.sv SYSTEM_VERILOG PATH ../../rtl/fifo_to_lane_bridge.sv
add_fileset_file altera_gpio_lite.sv SYSTEM_VERILOG PATH ../../rtl/generated/altera_gpio_lite.sv
add_fileset_file bidir.v VERILOG PATH ../../rtl/generated/bidir.v
add_fileset_file gpio.v VERILOG PATH ../../rtl/generated/gpio.v
add_fileset_file lvds_soft.v VERILOG PATH ../../rtl/generated/lvds_soft.v
add_fileset_file lvds_soft_0002.v VERILOG PATH ../../rtl/generated/lvds_soft_0002.v
add_fileset_file altera_generic_fifo.v VERILOG PATH ../../../common_modules/rtl/altera_generic_fifo.v
add_fileset_file avalon_mm_manager.v VERILOG PATH ../../../common_modules/rtl/avalon_mm_manager.v
add_fileset_file crc_modules.v VERILOG PATH ../../../common_modules/rtl/crc_modules.v
add_fileset_file sync_2ff.v VERILOG PATH ../../../common_modules/rtl/sync_2ff.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL dsi_tx_top
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_generic_fifo.v VERILOG PATH ../../../common_modules/rtl/altera_generic_fifo.v
add_fileset_file avalon_mm_manager.v VERILOG PATH ../../../common_modules/rtl/avalon_mm_manager.v
add_fileset_file crc_modules.v VERILOG PATH ../../../common_modules/rtl/crc_modules.v
add_fileset_file sync_2ff.v VERILOG PATH ../../../common_modules/rtl/sync_2ff.v
add_fileset_file dphy_tx_hs_lane.sv SYSTEM_VERILOG PATH ../../rtl/dphy_tx_hs_lane.sv
add_fileset_file dphy_tx_lane_full.sv SYSTEM_VERILOG PATH ../../rtl/dphy_tx_lane_full.sv
add_fileset_file dphy_tx_lanes_controller.sv SYSTEM_VERILOG PATH ../../rtl/dphy_tx_lanes_controller.sv
add_fileset_file dsi_tx_packets_assembler.v VERILOG PATH ../../rtl/dsi_tx_packets_assembler.v
add_fileset_file dsi_tx_pixel_buffer.v VERILOG PATH ../../rtl/dsi_tx_pixel_buffer.v
add_fileset_file dsi_tx_regs.v VERILOG PATH ../../rtl/dsi_tx_regs.v
add_fileset_file dsi_tx_top.v VERILOG PATH ../../rtl/dsi_tx_top.v
add_fileset_file fifo_to_lane_bridge.sv SYSTEM_VERILOG PATH ../../rtl/fifo_to_lane_bridge.sv
add_fileset_file altera_gpio_lite.sv SYSTEM_VERILOG PATH ../../rtl/generated/altera_gpio_lite.sv
add_fileset_file bidir.v VERILOG PATH ../../rtl/generated/bidir.v
add_fileset_file gpio.v VERILOG PATH ../../rtl/generated/gpio.v
add_fileset_file lvds_soft.v VERILOG PATH ../../rtl/generated/lvds_soft.v
add_fileset_file lvds_soft_0002.v VERILOG PATH ../../rtl/generated/lvds_soft_0002.v


# 
# parameters
# 
add_parameter LINE_WIDTH INTEGER 640
set_parameter_property LINE_WIDTH DEFAULT_VALUE 640
set_parameter_property LINE_WIDTH DISPLAY_NAME LINE_WIDTH
set_parameter_property LINE_WIDTH TYPE INTEGER
set_parameter_property LINE_WIDTH UNITS None
set_parameter_property LINE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LINE_WIDTH HDL_PARAMETER true
add_parameter BITS_PER_PIXEL INTEGER 8
set_parameter_property BITS_PER_PIXEL DEFAULT_VALUE 8
set_parameter_property BITS_PER_PIXEL DISPLAY_NAME BITS_PER_PIXEL
set_parameter_property BITS_PER_PIXEL TYPE INTEGER
set_parameter_property BITS_PER_PIXEL UNITS None
set_parameter_property BITS_PER_PIXEL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BITS_PER_PIXEL HDL_PARAMETER true
add_parameter BLANK_TIME INTEGER 100
set_parameter_property BLANK_TIME DEFAULT_VALUE 100
set_parameter_property BLANK_TIME DISPLAY_NAME BLANK_TIME
set_parameter_property BLANK_TIME TYPE INTEGER
set_parameter_property BLANK_TIME UNITS None
set_parameter_property BLANK_TIME ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BLANK_TIME HDL_PARAMETER true
add_parameter BLANK_TIME_HBP_ACT INTEGER 100
set_parameter_property BLANK_TIME_HBP_ACT DEFAULT_VALUE 100
set_parameter_property BLANK_TIME_HBP_ACT DISPLAY_NAME BLANK_TIME_HBP_ACT
set_parameter_property BLANK_TIME_HBP_ACT TYPE INTEGER
set_parameter_property BLANK_TIME_HBP_ACT UNITS None
set_parameter_property BLANK_TIME_HBP_ACT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BLANK_TIME_HBP_ACT HDL_PARAMETER true
add_parameter VSA_LINES_NUMBER INTEGER 100
set_parameter_property VSA_LINES_NUMBER DEFAULT_VALUE 100
set_parameter_property VSA_LINES_NUMBER DISPLAY_NAME VSA_LINES_NUMBER
set_parameter_property VSA_LINES_NUMBER TYPE INTEGER
set_parameter_property VSA_LINES_NUMBER UNITS None
set_parameter_property VSA_LINES_NUMBER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VSA_LINES_NUMBER HDL_PARAMETER true
add_parameter VBP_LINES_NUMBER INTEGER 100
set_parameter_property VBP_LINES_NUMBER DEFAULT_VALUE 100
set_parameter_property VBP_LINES_NUMBER DISPLAY_NAME VBP_LINES_NUMBER
set_parameter_property VBP_LINES_NUMBER TYPE INTEGER
set_parameter_property VBP_LINES_NUMBER UNITS None
set_parameter_property VBP_LINES_NUMBER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VBP_LINES_NUMBER HDL_PARAMETER true
add_parameter IMAGE_HEIGHT INTEGER 480 ""
set_parameter_property IMAGE_HEIGHT DEFAULT_VALUE 480
set_parameter_property IMAGE_HEIGHT DISPLAY_NAME IMAGE_HEIGHT
set_parameter_property IMAGE_HEIGHT TYPE INTEGER
set_parameter_property IMAGE_HEIGHT UNITS None
set_parameter_property IMAGE_HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property IMAGE_HEIGHT DESCRIPTION ""
set_parameter_property IMAGE_HEIGHT HDL_PARAMETER true
add_parameter VFP_LINES_NUMBER INTEGER 100
set_parameter_property VFP_LINES_NUMBER DEFAULT_VALUE 100
set_parameter_property VFP_LINES_NUMBER DISPLAY_NAME VFP_LINES_NUMBER
set_parameter_property VFP_LINES_NUMBER TYPE INTEGER
set_parameter_property VFP_LINES_NUMBER UNITS None
set_parameter_property VFP_LINES_NUMBER ALLOWED_RANGES -2147483648:2147483647
set_parameter_property VFP_LINES_NUMBER HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avl_mm
# 
add_interface avl_mm avalon end
set_interface_property avl_mm addressUnits WORDS
set_interface_property avl_mm associatedClock clock_system
set_interface_property avl_mm associatedReset reset_system_n
set_interface_property avl_mm bitsPerSymbol 8
set_interface_property avl_mm burstOnBurstBoundariesOnly false
set_interface_property avl_mm burstcountUnits WORDS
set_interface_property avl_mm explicitAddressSpan 0
set_interface_property avl_mm holdTime 0
set_interface_property avl_mm linewrapBursts false
set_interface_property avl_mm maximumPendingReadTransactions 0
set_interface_property avl_mm maximumPendingWriteTransactions 0
set_interface_property avl_mm readLatency 0
set_interface_property avl_mm readWaitTime 1
set_interface_property avl_mm setupTime 0
set_interface_property avl_mm timingUnits Cycles
set_interface_property avl_mm writeWaitTime 0
set_interface_property avl_mm ENABLED true
set_interface_property avl_mm EXPORT_OF ""
set_interface_property avl_mm PORT_NAME_MAP ""
set_interface_property avl_mm CMSIS_SVD_VARIABLES ""
set_interface_property avl_mm SVD_ADDRESS_GROUP ""

add_interface_port avl_mm avl_mm_address address Input 5
add_interface_port avl_mm avl_mm_read read Input 1
add_interface_port avl_mm avl_mm_readdata readdata Output 32
add_interface_port avl_mm avl_mm_response response Output 2
add_interface_port avl_mm avl_mm_write write Input 1
add_interface_port avl_mm avl_mm_writedata writedata Input 32
add_interface_port avl_mm avl_mm_byteenable byteenable Input 4
add_interface_port avl_mm avl_mm_waitrequest waitrequest Output 1
set_interface_assignment avl_mm embeddedsw.configuration.isFlash 0
set_interface_assignment avl_mm embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avl_mm embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avl_mm embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_system
set_interface_property avalon_streaming_sink associatedReset reset_system_n
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink in_avl_st_data data Input 32
add_interface_port avalon_streaming_sink in_avl_st_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink in_avl_st_ready ready Output 1
add_interface_port avalon_streaming_sink in_avl_st_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink in_avl_st_valid valid Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_system
set_interface_property interrupt_sender associatedReset reset_system_n
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point reset_system_n
# 
add_interface reset_system_n reset end
set_interface_property reset_system_n associatedClock clock_phy
set_interface_property reset_system_n synchronousEdges DEASSERT
set_interface_property reset_system_n ENABLED true
set_interface_property reset_system_n EXPORT_OF ""
set_interface_property reset_system_n PORT_NAME_MAP ""
set_interface_property reset_system_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_system_n SVD_ADDRESS_GROUP ""

add_interface_port reset_system_n rst_sys_n reset_n Input 1


# 
# connection point reset_phy_n
# 
add_interface reset_phy_n reset end
set_interface_property reset_phy_n associatedClock clock_system
set_interface_property reset_phy_n synchronousEdges DEASSERT
set_interface_property reset_phy_n ENABLED true
set_interface_property reset_phy_n EXPORT_OF ""
set_interface_property reset_phy_n PORT_NAME_MAP ""
set_interface_property reset_phy_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_phy_n SVD_ADDRESS_GROUP ""

add_interface_port reset_phy_n rst_phy_n reset_n Input 1


# 
# connection point clock_phy
# 
add_interface clock_phy clock end
set_interface_property clock_phy clockRate 0
set_interface_property clock_phy ENABLED true
set_interface_property clock_phy EXPORT_OF ""
set_interface_property clock_phy PORT_NAME_MAP ""
set_interface_property clock_phy CMSIS_SVD_VARIABLES ""
set_interface_property clock_phy SVD_ADDRESS_GROUP ""

add_interface_port clock_phy clk_phy clk Input 1


# 
# connection point clock_latch
# 
add_interface clock_latch clock end
set_interface_property clock_latch clockRate 0
set_interface_property clock_latch ENABLED true
set_interface_property clock_latch EXPORT_OF ""
set_interface_property clock_latch PORT_NAME_MAP ""
set_interface_property clock_latch CMSIS_SVD_VARIABLES ""
set_interface_property clock_latch SVD_ADDRESS_GROUP ""

add_interface_port clock_latch clk_hs_latch clk Input 1


# 
# connection point clock_hs
# 
add_interface clock_hs clock end
set_interface_property clock_hs clockRate 0
set_interface_property clock_hs ENABLED true
set_interface_property clock_hs EXPORT_OF ""
set_interface_property clock_hs PORT_NAME_MAP ""
set_interface_property clock_hs CMSIS_SVD_VARIABLES ""
set_interface_property clock_hs SVD_ADDRESS_GROUP ""

add_interface_port clock_hs clk_hs clk Input 1


# 
# connection point clock_hs_clk
# 
add_interface clock_hs_clk clock end
set_interface_property clock_hs_clk clockRate 0
set_interface_property clock_hs_clk ENABLED true
set_interface_property clock_hs_clk EXPORT_OF ""
set_interface_property clock_hs_clk PORT_NAME_MAP ""
set_interface_property clock_hs_clk CMSIS_SVD_VARIABLES ""
set_interface_property clock_hs_clk SVD_ADDRESS_GROUP ""

add_interface_port clock_hs_clk clk_hs_clk clk Input 1


# 
# connection point clock_system
# 
add_interface clock_system clock end
set_interface_property clock_system clockRate 0
set_interface_property clock_system ENABLED true
set_interface_property clock_system EXPORT_OF ""
set_interface_property clock_system PORT_NAME_MAP ""
set_interface_property clock_system CMSIS_SVD_VARIABLES ""
set_interface_property clock_system SVD_ADDRESS_GROUP ""

add_interface_port clock_system clk_sys clk Input 1


# 
# connection point DSI_interface
# 
add_interface DSI_interface conduit end
set_interface_property DSI_interface associatedClock ""
set_interface_property DSI_interface associatedReset ""
set_interface_property DSI_interface ENABLED true
set_interface_property DSI_interface EXPORT_OF ""
set_interface_property DSI_interface PORT_NAME_MAP ""
set_interface_property DSI_interface CMSIS_SVD_VARIABLES ""
set_interface_property DSI_interface SVD_ADDRESS_GROUP ""

add_interface_port DSI_interface dphy_data_hs_out_p dphy_data_hs_out_p Output 4
add_interface_port DSI_interface dphy_data_hs_out_n dphy_data_hs_out_n Output 4
add_interface_port DSI_interface dphy_data_lp_out_p dphy_data_lp_out_p Output 4
add_interface_port DSI_interface dphy_data_lp_out_n dphy_data_lp_out_n Output 4
add_interface_port DSI_interface dphy_clk_hs_out_p dphy_clk_hs_out_p Output 1
add_interface_port DSI_interface dphy_clk_hs_out_n dphy_clk_hs_out_n Output 1
add_interface_port DSI_interface dphy_clk_lp_out_p dphy_clk_lp_out_p Output 1
add_interface_port DSI_interface dphy_clk_lp_out_n dphy_clk_lp_out_n Output 1

